# Generated by Django 4.2.1 on 2023-06-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_carrito_categoria_direccionenvio_metodopago_resena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='DireccionEnvio',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
