# Generated by Django 4.2.1 on 2023-06-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ventas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='DireccionEnvio',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
